fit:
  trainer:
    max_epochs: 1500
    accelerator: cuda
    devices: 1
  data:
    dataset_name: losloop
    batch_size: 32
    seq_len: 12
    pre_len: 3
  model:
    model:
      class_path: models.TGCN
      init_args:
        hidden_dim: 64
    learning_rate: 0.001
    weight_decay: 0
    loss: mse_with_regularizer
